// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.3
// source: protos/application.proto

package genprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	WeatherService_GetWeatherByCountryName_FullMethodName = "/WeatherService/GetWeatherByCountryName"
)

// WeatherServiceClient is the client API for WeatherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeatherServiceClient interface {
	GetWeatherByCountryName(ctx context.Context, in *GetWeatherByCountryNameReq, opts ...grpc.CallOption) (WeatherService_GetWeatherByCountryNameClient, error)
}

type weatherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeatherServiceClient(cc grpc.ClientConnInterface) WeatherServiceClient {
	return &weatherServiceClient{cc}
}

func (c *weatherServiceClient) GetWeatherByCountryName(ctx context.Context, in *GetWeatherByCountryNameReq, opts ...grpc.CallOption) (WeatherService_GetWeatherByCountryNameClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WeatherService_ServiceDesc.Streams[0], WeatherService_GetWeatherByCountryName_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &weatherServiceGetWeatherByCountryNameClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WeatherService_GetWeatherByCountryNameClient interface {
	Recv() (*GetWeatherByCountryNameRes, error)
	grpc.ClientStream
}

type weatherServiceGetWeatherByCountryNameClient struct {
	grpc.ClientStream
}

func (x *weatherServiceGetWeatherByCountryNameClient) Recv() (*GetWeatherByCountryNameRes, error) {
	m := new(GetWeatherByCountryNameRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WeatherServiceServer is the server API for WeatherService service.
// All implementations must embed UnimplementedWeatherServiceServer
// for forward compatibility
type WeatherServiceServer interface {
	GetWeatherByCountryName(*GetWeatherByCountryNameReq, WeatherService_GetWeatherByCountryNameServer) error
	mustEmbedUnimplementedWeatherServiceServer()
}

// UnimplementedWeatherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeatherServiceServer struct {
}

func (UnimplementedWeatherServiceServer) GetWeatherByCountryName(*GetWeatherByCountryNameReq, WeatherService_GetWeatherByCountryNameServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWeatherByCountryName not implemented")
}
func (UnimplementedWeatherServiceServer) mustEmbedUnimplementedWeatherServiceServer() {}

// UnsafeWeatherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherServiceServer will
// result in compilation errors.
type UnsafeWeatherServiceServer interface {
	mustEmbedUnimplementedWeatherServiceServer()
}

func RegisterWeatherServiceServer(s grpc.ServiceRegistrar, srv WeatherServiceServer) {
	s.RegisterService(&WeatherService_ServiceDesc, srv)
}

func _WeatherService_GetWeatherByCountryName_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetWeatherByCountryNameReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WeatherServiceServer).GetWeatherByCountryName(m, &weatherServiceGetWeatherByCountryNameServer{ServerStream: stream})
}

type WeatherService_GetWeatherByCountryNameServer interface {
	Send(*GetWeatherByCountryNameRes) error
	grpc.ServerStream
}

type weatherServiceGetWeatherByCountryNameServer struct {
	grpc.ServerStream
}

func (x *weatherServiceGetWeatherByCountryNameServer) Send(m *GetWeatherByCountryNameRes) error {
	return x.ServerStream.SendMsg(m)
}

// WeatherService_ServiceDesc is the grpc.ServiceDesc for WeatherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WeatherService",
	HandlerType: (*WeatherServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWeatherByCountryName",
			Handler:       _WeatherService_GetWeatherByCountryName_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/application.proto",
}
