// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: protos/application.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherByCountryNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryName string `protobuf:"bytes,1,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
}

func (x *GetWeatherByCountryNameReq) Reset() {
	*x = GetWeatherByCountryNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_application_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherByCountryNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherByCountryNameReq) ProtoMessage() {}

func (x *GetWeatherByCountryNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_application_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherByCountryNameReq.ProtoReflect.Descriptor instead.
func (*GetWeatherByCountryNameReq) Descriptor() ([]byte, []int) {
	return file_protos_application_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeatherByCountryNameReq) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

type GetWeatherByCountryNameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryName string  `protobuf:"bytes,1,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	Temperature float32 `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
}

func (x *GetWeatherByCountryNameRes) Reset() {
	*x = GetWeatherByCountryNameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_application_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWeatherByCountryNameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherByCountryNameRes) ProtoMessage() {}

func (x *GetWeatherByCountryNameRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_application_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherByCountryNameRes.ProtoReflect.Descriptor instead.
func (*GetWeatherByCountryNameRes) Descriptor() ([]byte, []int) {
	return file_protos_application_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherByCountryNameRes) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *GetWeatherByCountryNameRes) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

var File_protos_application_proto protoreflect.FileDescriptor

var file_protos_application_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x32, 0x67,
	0x0a, 0x0e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x55, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x42, 0x79,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x2e, 0x47, 0x65,
	0x74, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x65,
	0x61, 0x74, 0x68, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_application_proto_rawDescOnce sync.Once
	file_protos_application_proto_rawDescData = file_protos_application_proto_rawDesc
)

func file_protos_application_proto_rawDescGZIP() []byte {
	file_protos_application_proto_rawDescOnce.Do(func() {
		file_protos_application_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_application_proto_rawDescData)
	})
	return file_protos_application_proto_rawDescData
}

var file_protos_application_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_application_proto_goTypes = []any{
	(*GetWeatherByCountryNameReq)(nil), // 0: GetWeatherByCountryNameReq
	(*GetWeatherByCountryNameRes)(nil), // 1: GetWeatherByCountryNameRes
}
var file_protos_application_proto_depIdxs = []int32{
	0, // 0: WeatherService.GetWeatherByCountryName:input_type -> GetWeatherByCountryNameReq
	1, // 1: WeatherService.GetWeatherByCountryName:output_type -> GetWeatherByCountryNameRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_application_proto_init() }
func file_protos_application_proto_init() {
	if File_protos_application_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_application_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetWeatherByCountryNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_application_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetWeatherByCountryNameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_application_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_application_proto_goTypes,
		DependencyIndexes: file_protos_application_proto_depIdxs,
		MessageInfos:      file_protos_application_proto_msgTypes,
	}.Build()
	File_protos_application_proto = out.File
	file_protos_application_proto_rawDesc = nil
	file_protos_application_proto_goTypes = nil
	file_protos_application_proto_depIdxs = nil
}
